### ISSUE TITLE
Fails to compile in 0.13

### ISSUE THREAD

**Issue by knewter** [myfreeweb/httpotion#24]
I don't think it's a big deal, but `httpotion` presently fails to compile in 0.13.  Here's the error if you want to see it:

```
* Compiling httpotion
== Compilation error on file lib/httpotion.ex ==
could not compile dependency httpotion, mix compile failed. You can recompile this dependency with `mix deps.compile httpotion` or update it with `mix deps.update httpotion`
** (SyntaxError) deps/httpotion/lib/httpotion.ex:9: invalid token: \Ahttps?:\/\// do
    (elixir) lib/kernel/parallel_compiler.ex:91: anonymous fn/3 in Kernel.ParallelCompiler.spawn_compilers/8
```

Anyway, thought it might be helpful to have this reported.  Thanks!
